---
# Configure GUI service and performance collection

# Make default variables available in hostvars
- name: cluster | Set default collector role
  set_fact:
    scale_gui_collector: "{{ scale_gui_collector }}"
  when: hostvars[inventory_hostname].scale_gui_collector is undefined

#
# Inspect inventory
#
- name: configure | Find collector nodes
  add_host:
    name: "{{ item }}"
    groups: scale_gui_collectors
  when: hostvars[item].scale_gui_collector | bool
  with_items: "{{ ansible_play_hosts }}"
  changed_when: false

#
# Configure performance collection
#
- name: configure | Start and enable GUI service
  systemd:
    name: gpfsgui
    state: started
    enabled: true
  when: scale_gui_collector | bool

- name: configure | Check if initialize performance collection is already configured.
  shell: "/usr/lpp/mmfs/bin/mmperfmon config show | grep colCandidates"
  register: scale_gui_conf_pmcollector_check
  run_once: true
  failed_when: false
  changed_when: false
  when:
    - scale_gui_collector | bool

- name: configure | Check if initialize performance collection is already configured - Output stdout
  run_once: true
  debug:
    msg: "{{ scale_gui_conf_pmcollector_check.stdout }}"
    verbosity: 2
  when:
    - scale_gui_collector | bool

- name: configure | Check if initialize performance collection is already configured - Output stderr
  run_once: true
  debug:
    msg: "{{ scale_gui_conf_pmcollector_check.stderr }}"
    verbosity: 2
  when:
    - scale_gui_collector | bool

#TODO: Ole Kristian: added a check for output, but are having problems using the ( collector_nodes | join(',') ) to use when adding nodes.
- name: configure | Initialize performance collection
  vars:
    collector_nodes: "{{ groups['scale_gui_collectors'] | list }}"
  command: /usr/lpp/mmfs/bin/mmperfmon config generate --collectors {{ collector_nodes | join(',') }}
  register: scale_gui_conf_pmcollector
  when:
    - scale_gui_collector | bool
    - " 'mmperfmon: There is no performance monitoring configuration data.' in scale_gui_conf_pmcollector_check.stderr"
#- " ( collector_nodes | join(',') ) not in scale_gui_conf_pmcollector_check.stdout"
  run_once: true

#
# PM sensors - all host will now have Performance Monitoring installed and configured.
#
- name: configure | Check before enable nodes for performance collection #TODO: Only checks first node for perfmon.
  vars:
    sensor_nodes: "{{ ansible_play_hosts | list }}"
  shell: "/usr/lpp/mmfs/bin/mmlscluster -Y | grep -v HEADER | grep clusterNode |grep {{ sensor_nodes | first }} | cut -d ':' -f 14"
  register: scale_gui_conf_perfmon_check
  run_once: true
  failed_when: false
  changed_when: false

- name: configure | Check before enable nodes for performance collection - Output stdout
  run_once: true
  debug:
    msg: "{{ scale_gui_conf_perfmon_check.stdout }}"
    verbosity: 2

- name: configure | Enable nodes for performance collection #TODO discuss: should it be dependent on scale_gui_collector?
  vars:
    sensor_nodes: "{{ ansible_play_hosts | list }}"
  command: /usr/lpp/mmfs/bin/mmchnode --perfmon -N {{ sensor_nodes | join(',') }}
  register: scale_gui_conf_enable_node_perfmon
  run_once: true
  ignore_errors: yes
  failed_when: "scale_gui_conf_enable_node_perfmon.rc != 0 and 'Propagating the cluster configuration data to all affected nodes.' not in scale_gui_conf_enable_node_perfmon.stdout"
  when:
    - scale_gui_collector | bool
    - " 'perfmon' not in scale_gui_conf_perfmon_check.stdout"

#
# Start and enable PMCollector and PM Sensors.
#

- name: configure | Start and enable collector service
  systemd:
    name: pmcollector
    state: started
    enabled: true
  when: scale_gui_collector | bool

- name: configure | Start and enable sensors service
  systemd:
    name: pmsensors
    state: started
    enabled: true
#
# Initialize the GUI so that user dont need to wait and HTTPs certificate and be imported.
#
- name: configure | Initialize the GUI
  command: /usr/lpp/mmfs/gui/cli/initgui
  register: scale_gui_conf_initgui
  failed_when: "scale_gui_conf_initgui.rc != 0 and 'EFSSG1000I' not in scale_gui_conf_initgui.stdout"
  when: scale_gui_collector | bool
  #TODO check: don't know what to check if the init is already run